const INSTALLER_LATEST_VERSION = "6.0.0";
const INSTALLER_MINIMUM_ALLOWED_VERSION = "6.0.0";
const MINIMUM_COMPATIBLE_FTCLIVE_VERSION = "4.1.1";
const LATEST_TESTED_FTCLIVE_VERSION = "4.1.5";

module.exports = {
  INSTALLER_LATEST_VERSION,
  INSTALLER_MINIMUM_ALLOWED_VERSION,
  MINIMUM_COMPATIBLE_FTCLIVE_VERSION,
  LATEST_TESTED_FTCLIVE_VERSION
}
